AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 + EC2 template"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket-2025-09-07

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0009f0c4964e4e0f9

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
  EC2InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref MyEC2Instance
